'use strict';
const N=8, TYPES=6;
const images=Array.from({length:TYPES},(_,i)=>`assets/${i+1}.${i===4?'jpg':'png'}`);
const powers={bomb:{image:'assets/bomb.jpg',name:'范围炸弹',badge:'3×3'},line:{image:'assets/line.jpg',name:'直线道具',badge:'↔'},color:{image:'assets/color.jpg',name:'同类全消',badge:'全消'},cross:{image:'assets/cross.png',name:'十字道具',badge:'＋'}};
function analyze(b){const groups=[],hit=new Set;const val=(r,c)=>b[r]?.[c]&&!b[r][c].special?b[r][c].type:null;
for(let r=0;r<N;r++)for(let c=0;c<N;c++){const v=val(r,c);if(v==null)continue;for(const [dr,dc,axis]of [[0,1,'row'],[1,0,'col']]){if(val(r-dr,c-dc)===v)continue;const cells=[];let rr=r,cc=c;while(rr<N&&cc<N&&val(rr,cc)===v){cells.push(rr*N+cc);rr+=dr;cc+=dc;}if(cells.length>=3)groups.push({cells,axis});}if(r<N-1&&c<N-1&&val(r,c+1)===v&&val(r+1,c)===v&&val(r+1,c+1)===v)groups.push({cells:[r*N+c,r*N+c+1,(r+1)*N+c,(r+1)*N+c+1],axis:'square'});}
for(const g of groups)for(const p of g.cells)hit.add(p);
const components=[];for(const g of groups){const overlaps=components.filter(x=>g.cells.some(p=>x.cells.has(p)));const x={cells:new Set(g.cells),groups:[g]};for(const o of overlaps){for(const p of o.cells)x.cells.add(p);x.groups.push(...o.groups);components.splice(components.indexOf(o),1);}components.push(x);}return{hit,components};}
function matches(b){return analyze(b).hit;}
function rewards(info,preferred=[]){const result=[];for(const x of info.components){const lines=x.groups.filter(g=>g.axis!=='square');const five=lines.find(g=>g.cells.length>=5),cross=lines.find(g=>lines.some(h=>h.axis!==g.axis&&g.cells.some(p=>h.cells.includes(p)))),four=lines.find(g=>g.cells.length===4),square=x.groups.find(g=>g.axis==='square');let special,axis,cells;if(five){special='color';cells=five.cells;}else if(cross){special='cross';cells=x.cells;}else if(four){special='line';axis=four.axis;cells=four.cells;}else if(square){special='bomb';cells=square.cells;}else continue;const all=[...cells];const p=preferred.find(p=>all.includes(p))??(special==='cross'?lines.find(g=>g.axis==='row')?.cells.find(p=>lines.some(h=>h.axis==='col'&&h.cells.includes(p))):null)??all[Math.floor(all.length/2)];result.push({p,special,axis});}return result;}
function blast(b,initial){const hit=new Set(initial),triggered=new Set;let changed=true;while(changed){changed=false;for(const p of [...hit]){const r=Math.floor(p/N),c=p%N,t=b[r]?.[c];if(!t?.special||triggered.has(p))continue;triggered.add(p);changed=true;const add=(rr,cc)=>{if(rr>=0&&rr<N&&cc>=0&&cc<N&&b[rr][cc])hit.add(rr*N+cc);};if(t.special==='bomb')for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)add(r+dr,c+dc);if(t.special==='line'||t.special==='cross')for(let k=0;k<N;k++){if(t.special==='cross'||t.axis==='row')add(r,k);if(t.special==='cross'||t.axis==='col')add(k,c);}if(t.special==='color')for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(b[rr][cc]?.type===t.type)add(rr,cc);}}return hit;}
function swap(b,a,z){[b[a.r][a.c],b[z.r][z.c]]=[b[z.r][z.c],b[a.r][a.c]];}
function possible(b){if(b.some(row=>row.some(t=>t?.special)))return true;for(let r=0;r<N;r++)for(let c=0;c<N;c++)for(const [dr,dc]of [[0,1],[1,0]]){const a={r,c},z={r:r+dr,c:c+dc};if(z.r>=N||z.c>=N)continue;swap(b,a,z);const ok=matches(b).size;swap(b,a,z);if(ok)return true;}return false;}
const boardEl=document.getElementById('board'),statusEl=document.getElementById('status'),restart=document.getElementById('restart');
let board=[],uid=0,selected=null,busy=false,score=0,moves=0,best=0;const nodes=new Map;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const fresh=()=>({type:Math.floor(Math.random()*TYPES),id:++uid});
function counters(){document.getElementById('score').textContent=score.toLocaleString('zh-CN');document.getElementById('moves').textContent=moves;document.getElementById('best').textContent=best;}
function skin(e,t){const key=t.special?`${t.special}:${t.axis||''}`:`normal:${t.type}`;if(e.dataset.skin===key)return;e.dataset.skin=key;e.innerHTML=`<img draggable="false" alt="" src="${t.special?powers[t.special].image:images[t.type]}">${t.special?`<span class="power-badge">${t.special==='line'&&t.axis==='col'?'↕':powers[t.special].badge}</span>`:''}`;e.classList.toggle('power',!!t.special);e.title=t.special?powers[t.special].name+' · 点击使用':'';}
function tileNode(t,r,c){const e=document.createElement('button');e.className='tile';e.type='button';skin(e,t);position(e,r,c);boardEl.append(e);nodes.set(t.id,e);return e;}
function position(e,r,c){e.style.transform=`translate(${c*100}%,${r*100}%)`;e.dataset.r=r;e.dataset.c=c;e.setAttribute('aria-label',`第${r+1}行第${c+1}列，${board[r]?.[c]?.special?powers[board[r][c].special].name+'，点击使用':'表情'+(board[r]?.[c]?.type+1||'')}`);}
function draw(){for(let r=0;r<N;r++)for(let c=0;c<N;c++){const t=board[r][c];if(!t)continue;const e=nodes.get(t.id)||tileNode(t,r,c);position(e,r,c);skin(e,t);e.classList.toggle('selected',selected?.r===r&&selected?.c===c);e.setAttribute('aria-pressed',String(selected?.r===r&&selected?.c===c));}}
function makeBoard(){do{board=Array.from({length:N},()=>Array(N).fill(null));for(let r=0;r<N;r++)for(let c=0;c<N;c++){let t;do{t=fresh();}while(c>=2&&board[r][c-1].type===t.type&&board[r][c-2].type===t.type||r>=2&&board[r-1][c].type===t.type&&board[r-2][c].type===t.type||r>=1&&c>=1&&board[r][c-1].type===t.type&&board[r-1][c].type===t.type&&board[r-1][c-1].type===t.type);board[r][c]=t;}}while(!possible(board));}
function newGame(){if(busy)return;selected=null;score=0;moves=0;best=0;boardEl.replaceChildren();nodes.clear();makeBoard();counters();draw();statusEl.textContent='三连或 2×2 都能消除，交换相邻表情试试。';document.getElementById('combo').textContent='来一场快乐连消';}
async function resolve(initial=null,preferred=[]){let chain=0,seed=initial;while(true){const info=analyze(board);let hit=seed?new Set(seed):new Set(info.hit);if(!hit.size)break;let gifts=seed?[]:rewards(info,preferred);seed=null;preferred=[];for(const g of gifts)hit.delete(g.p);hit=blast(board,hit);gifts=gifts.filter(g=>!hit.has(g.p));chain++;best=Math.max(best,chain);const points=hit.size*10*chain;score+=points;counters();document.getElementById('combo').textContent=gifts.length?'道具出现！点击使用':chain>1?`${chain} 连消！`:'漂亮，消掉了！';const f=document.getElementById('float');f.classList.remove('show');void f.offsetWidth;f.textContent=`+${points}`;f.classList.add('show');for(const p of hit)nodes.get(board[Math.floor(p/N)][p%N].id).classList.add('clear');await pause(270);for(const p of hit){const r=Math.floor(p/N),c=p%N,t=board[r][c];nodes.get(t.id).remove();nodes.delete(t.id);board[r][c]=null;}for(const g of gifts){const t=board[Math.floor(g.p/N)][g.p%N];t.special=g.special;t.axis=g.axis;}draw();
for(let c=0;c<N;c++){const kept=[];for(let r=0;r<N;r++)if(board[r][c])kept.push(board[r][c]);const count=N-kept.length;for(let r=0;r<count;r++){board[r][c]=fresh();tileNode(board[r][c],r-count,c);}for(let r=count;r<N;r++)board[r][c]=kept[r-count];}void boardEl.offsetWidth;draw();await pause(290);}
if(!possible(board)){statusEl.textContent='没有可消除的交换，正在自动换一盘…';await pause(350);boardEl.replaceChildren();nodes.clear();makeBoard();draw();statusEl.textContent='已自动换盘，分数继续累积。';}else statusEl.textContent=board.some(row=>row.some(t=>t.special))?'金色边框的是道具，点击即可使用。':chain>1?`完成 ${chain} 连消，继续！`:'消除成功，再来一组！';}
async function activate(p){if(busy||!board[p.r][p.c]?.special)return false;busy=true;restart.disabled=true;selected=null;draw();await resolve(new Set([p.r*N+p.c]));busy=false;restart.disabled=false;return true;}
async function exchange(a,z){if(busy)return false;if(Math.abs(a.r-z.r)+Math.abs(a.c-z.c)!==1)return false;busy=true;restart.disabled=true;selected=null;swap(board,a,z);draw();await pause(250);const specials=[a,z].filter(p=>board[p.r][p.c]?.special);const ok=specials.length>0||matches(board).size>0;if(!ok){swap(board,a,z);draw();statusEl.textContent='没有形成三连或 2×2，试试其他交换。';document.getElementById('combo').textContent='寻找下一个三连';await pause(250);}else{moves++;counters();if(specials.length)await resolve(new Set(specials.map(p=>p.r*N+p.c)));else await resolve(null,[z.r*N+z.c,a.r*N+a.c]);}busy=false;restart.disabled=false;return ok;}
function select(p){if(busy)return;if(board[p.r][p.c]?.special){void activate(p);return;}if(!selected){selected=p;statusEl.textContent='已选中，再点一个相邻表情。';draw();return;}if(selected.r===p.r&&selected.c===p.c){selected=null;draw();return;}if(Math.abs(selected.r-p.r)+Math.abs(selected.c-p.c)===1){void exchange(selected,p);}else{selected=p;draw();statusEl.textContent='已更换选择，请点它旁边的表情。';}}
let down=null,ignoreClick=false;
boardEl.addEventListener('pointerdown',e=>{const t=e.target.closest('.tile');if(!t||busy)return;down={x:e.clientX,y:e.clientY,r:+t.dataset.r,c:+t.dataset.c};});
boardEl.addEventListener('pointerup',e=>{if(!down)return;const a=down;down=null;const dx=e.clientX-a.x,dy=e.clientY-a.y;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;ignoreClick=true;setTimeout(()=>ignoreClick=false,50);const z={r:a.r,c:a.c};if(Math.abs(dx)>Math.abs(dy))z.c+=Math.sign(dx);else z.r+=Math.sign(dy);if(z.r>=0&&z.r<N&&z.c>=0&&z.c<N)void exchange(a,z);});
boardEl.addEventListener('pointercancel',()=>down=null);
boardEl.addEventListener('click',e=>{if(ignoreClick)return;const t=e.target.closest('.tile');if(t)select({r:+t.dataset.r,c:+t.dataset.c});});
boardEl.addEventListener('keydown',e=>{const t=e.target.closest('.tile');if(!t)return;const dirs={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(!dirs[e.key])return;e.preventDefault();const [dr,dc]=dirs[e.key],r=+t.dataset.r+dr,c=+t.dataset.c+dc;if(r>=0&&r<N&&c>=0&&c<N)nodes.get(board[r][c].id).focus();});
restart.addEventListener('click',newGame);document.getElementById('cast').innerHTML=images.map(src=>`<img src="${src}" alt="">`).join('');newGame();
if(document.modelContext?.registerTool){for(const t of [{name:'read_game',description:'读取当前棋盘、分数和忙碌状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({board:board.map(row=>row.map(t=>({type:t.type+1,special:t.special||null,axis:t.axis||null}))),score,moves,busy})},{name:'swap_tiles',description:'交换两个相邻图标，等待消除和下落完成；行列从0到7。',inputSchema:{type:'object',properties:{r:{type:'integer',minimum:0,maximum:7},c:{type:'integer',minimum:0,maximum:7},direction:{type:'string',enum:['up','down','left','right']}},required:['r','c','direction'],additionalProperties:false},execute:async input=>{const {r,c,direction}=input||{},d={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]}[direction];if(!Number.isInteger(r)||!Number.isInteger(c)||r<0||r>=N||c<0||c>=N||!d)throw Error('无效位置或方向');const z={r:r+d[0],c:c+d[1]};if(z.r<0||z.r>=N||z.c<0||z.c>=N||busy)throw Error('暂不能交换');const matched=await exchange({r,c},z);return{matched,score,moves};}}]){try{Promise.resolve(document.modelContext.registerTool(t)).catch(()=>{});}catch{}}}
